Repository wecode-bootcamp-korea/19-2nd-CareOfLegend-frontend, pull requests merged in 2021-05, with the labels that each got.

#3 [19기 서동이] nav 카테고리 드롭기능구현
  Icon 
  package-lock.json
  package.json
  public/Data/Dong/NavDropData.json
  public/Images/btn1.jpg
  src/Components/Nav/Component/LearnDrop.js
  src/Components/Nav/Component/ProfileBox.js
  src/Components/Nav/Component/ProfileDrop.js
  src/Components/Nav/Component/ShopDrop.js
  src/Components/Nav/Nav.js
  src/Config.js
  src/Pages/Main/Main.js
  src/Pages/Main/btn2.jpg
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/index.js
Labels: Status: Rebase 요청

#4 [19기 서동이] Main 리뷰반영 완료
  public/Data/Dong/Dong.json
  src/Pages/Main/Image/btn1.jpg
  src/Pages/Main/Image/btn2.jpg
  src/Pages/Main/Image/main.jpg
  src/Pages/Main/Main.js
  src/Pages/Main/component/MainCard.js
  src/Styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#6 [19기 서동이] Nav- shopDrop 글씨 색 변경 호버 기능 수정
  Icon 
  src/Components/Nav/Component/ShopDrop.js
  src/Components/Nav/Nav.js
Labels: Status: 리뷰 요청

#1 [19기 김희열] Add: Login data axios complete with BE.
  package-lock.json
  package.json
  public/Images/Camera.png
  public/index.html
  src/Components/Nav/Component/ShopDrop.js
  src/Components/Nav/Nav.js
  src/Config.js
  src/Pages/Login/Login.js
  src/Pages/Login/component/WelcomeModal.js
  yarn.lock
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [19기 서동이] 각 페이지 링크 수정
  src/Components/Nav/Nav.js
Labels: Status: Conflict 발생

#2 [19기 서민석] 백엔드 연결 테스트 완료 코드리뷰 수정 완료 , nav 마지막 수정완료
  public/Data/Min/Cards.json
  public/Data/Min/LeftCategory.json
  public/Data/Min/LeftCategory2.json
  public/Data/Min/Min.json
  src/Config.js
  src/Pages/ProductList/Components/Card.js
  src/Pages/ProductList/Components/Category.js
  src/Pages/ProductList/Components/Contents.js
  src/Pages/ProductList/Components/FrontDisplay.js
  src/Pages/ProductList/Components/Main.js
  src/Pages/ProductList/Components/ProductListNav.js
  src/Pages/ProductList/ProductList.js
Labels: Status: 수정 요청

#5 [19기 서동이] Add: 퀴즈 데이터 수정
  package-lock.json
  public/Data/Dong/QuizData.json
  public/Data/Dong/ResultData.json
  public/Images/capsule.jpg
  public/Images/capsule2.jpg
  public/Images/capsule3.jpg
  public/Images/care.png
  public/Images/heart.png
  public/Images/smile.png
  public/Images/smileH.png
  public/Images/끼야.png
  src/Components/Nav/Nav.js
  src/Config.js
  src/Pages/Quiz/Greeting.js
  src/Pages/Quiz/Intro.js
  src/Pages/Quiz/QnATemplate.js
  src/Pages/Quiz/Quiz.js
  src/Pages/Quiz/Result.js
  src/Pages/Quiz/components/BoxSelectCard.js
  src/Pages/Quiz/components/CheckBtn.js
  src/Pages/Quiz/components/CheckGoal.js
  src/Pages/Quiz/components/FiftyFifty.js
  src/Pages/Quiz/components/ProductCard.js
  src/Pages/Quiz/components/QuizNav.js
  src/Pages/Quiz/components/WriteInfo.js
  src/Pages/Quiz/images/care.png
  src/Pages/Quiz/images/intro.jpg
  src/Pages/Quiz/images/result.jpg
  src/Pages/Quiz/images/result2.jpg
  src/Pages/Quiz/images/result3.jpg
  src/Pages/Quiz/images/smileH.png
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#8 [19기 서민석] 충돌 해결
  public/Data/Min/Basket.json
  src/Config.js
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Components/BasketProducts.js
  src/Pages/Basket/Components/Main.js
  src/Pages/Basket/Components/Total.js
  src/Routes.js
Labels: Status: 리뷰 요청

#10 [19기 서동이] quiz -Add: 진짜 최종
  public/Data/Dong/GoodsInfo.json
  public/Data/Dong/QuizData.json
  src/Pages/Quiz/QnATemplate.js
  src/Pages/Quiz/Quiz.js
  src/Pages/Quiz/Result.js
  src/Pages/Quiz/components/CheckBtn.js
  src/Pages/Quiz/components/CheckGoal.js
  src/Pages/Quiz/components/FiftyFifty.js
  src/Pages/Quiz/components/WriteInfo.js
Labels: Status: 리뷰 요청
